UPST/Models/ErrorViewModel.cs
namespace UPST.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UPST/Controllers/ArticlesController.cs
using Microsoft.AspNetCore.Mvc;

namespace UPST.Controllers
{
    public class ArticlesController : Controller
    {
        [HttpGet("/artikel")]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail()
        {
            return View();
        }


    }
}

UPST/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UPST.Models;

namespace UPST.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UPST/Controllers/KontakController.cs
using Microsoft.AspNetCore.Mvc;

namespace UPST.Controllers
{
    public class KontakController : Controller
    {
        [HttpGet("/kontak")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

UPST/Controllers/PengelolaanSampahController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace UPST.Controllers
{
    public class PengelolaanSampahController : Controller
    {

        // TPST Bantargebang
        [HttpGet("/tpst-bantargebang/ringkasan")]
        public IActionResult TPSTRingkasan() =>  View("~/Views/PengelolaanSampah/TPST/Ringkasan.cshtml");
        [HttpGet("/tpst-bantargebang/data")]
        public IActionResult TPSTData() => View("~/Views/PengelolaanSampah/TPST/Data.cshtml");
        [HttpGet("/tpst-bantargebang/landfill")]
        public IActionResult TPSTLandfill() => View("~/Views/PengelolaanSampah/TPST/Landfill.cshtml");
        [HttpGet("/tpst-bantargebang/pltsa")]
        public IActionResult TPSTPLTSA() => View("~/Views/PengelolaanSampah/TPST/PLTSA.cshtml");
        [HttpGet("/tpst-bantargebang/faq")]
        public IActionResult TPSTFAQ() => View("~/Views/PengelolaanSampah/TPST/FAQ.cshtml");



        // PKM
        [HttpGet("/pkm/ringkasan")]
        public IActionResult PKMRingkasan() => View("~/Views/PengelolaanSampah/PKM/Ringkasan.cshtml");
        [HttpGet("/pkm/data")]
        public IActionResult PKMData() => View("~/Views/PengelolaanSampah/PKM/Data.cshtml");
        [HttpGet("/pkm/faq")]
        public IActionResult PKMFAQ() => View("~/Views/PengelolaanSampah/PKM/FAQ.cshtml");



        // ITF
        [HttpGet("/itf/ringkasan")]
        public IActionResult ITFRingkasan() => View("~/Views/PengelolaanSampah/ITF/Ringkasan.cshtml");
        [HttpGet("/itf/data")]
        public IActionResult ITFData() => View("~/Views/PengelolaanSampah/ITF/Data.cshtml");
        [HttpGet("/itf/faq")]
        public IActionResult ITFFAQ() => View("~/Views/PengelolaanSampah/ITF/FAQ.cshtml");



        // JRC
        [HttpGet("/jrc/ringkasan")]
        public IActionResult JRCRingkasan() => View("~/Views/PengelolaanSampah/JRC/Ringkasan.cshtml");
        [HttpGet("/jrc/mekanisme")]
        public IActionResult JRCMekanisme() => View("~/Views/PengelolaanSampah/JRC/Mekanisme.cshtml");

    }
}

UPST/Controllers/ProdukController.cs
using Microsoft.AspNetCore.Mvc;

namespace UPST.Controllers
{
    public class ProdukController : Controller
    {
        [HttpGet("/produk")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

UPST/Controllers/ProdukHukumController.cs
using System.IO;
using Microsoft.AspNetCore.Mvc;

namespace UPST.Controllers

{
    public class ProdukHukumController : Controller
    {

        [HttpGet("/produk-hukum")]
        public IActionResult Index()
        {
            return View();
        }

    }
}

UPST/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace UPST.Controllers
{
    public class ProfileController : Controller
    {

        // Profil
        [HttpGet("/profil/tentang-kami")]
        public IActionResult Index() => View();

        [HttpGet("/profil/struktur-organisasi")]
        public IActionResult StrukturOrganisasi() => View();

        [HttpGet("/profil/galeri")]
        public IActionResult Galeri() => View();

    }
}

UPST/Views/Kontak/Index.cshtml
@{
    ViewData["Title"] = "Hubungi Kami";
    ViewBag.Menu = "Kontak";
}

<main class="container responsive pb-5" style="padding-top: 120px; width: 75%">
    <section class="text-center">
        <h1 class="fw-bold" style="font-size: 3.8rem">@ViewData["Title"]</h1>
        <p class="text-muted fs-4">
            Kunjungi kami atau hubungi kami melalui cara dibawah ini:
        </p>
    </section>
    <section class="content px-2 px-lg-3 pt-3 pb-0 pb-lg-5">
        <div class="row justify-content-center">
            <div class="col">
                <div class="row mt-3" style="--bs-gutter-x: 4rem">
                    <div class="col-md-6">
                        <div class="card p-4 rounded-lg">
                            <form class="needs-validation" novalidate>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-floating mb-4">
                                            <input type="text"
                                                   class="form-control fw-bold"
                                                   id="floatingInput"
                                                   autocomplete="off"
                                                   placeholder="Nama Lengkap" required />
                                            <label for="floatingInput">Nama Lengkap <span class="text-danger">*</span></label>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-floating mb-4">
                                            <input type="email"
                                                   class="form-control fw-bold"
                                                   id="floatingInput"
                                                   autocomplete="off"
                                                   placeholder="name@example.com" required />
                                            <label for="floatingInput">Alamat Email <span class="text-danger">*</span></label>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-floating mb-4">
                                            <input type="text"
                                                   class="form-control fw-bold"
                                                   id="floatingInput"
                                                   autocomplete="off"
                                                   placeholder="Nomor Handphone" required />
                                            <label for="floatingInput">Judul <span class="text-danger">*</span></label>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-floating mb-4 mb-lg-2">
                                            <select class="form-select fw-bold" id="floatingSelect" aria-label="Floating label select example" required>
                                                <option value="" disabled selected>Pilih Kategori</option>
                                                <option value="1">UPST</option>
                                                <option value="2">TPST Bantargebang</option>
                                                <option value="3">PKM</option>
                                                <option value="4">ITF</option>
                                                <option value="5">JRC</option>
                                                <option value="6">Lainnya</option>
                                            </select>
                                            <label for="floatingSelect">Kategori <span class="text-danger">*</span></label>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-floating mb-4">
                                            <textarea class="form-control fw-bold" placeholder="Leave a comment here" id="floatingTextarea" style="resize: none; overscroll-behavior-y:none; height: unset;" rows="3" autocomplete="off" autocapitalize="off" autocorrect="off" required></textarea>
                                            <label for="floatingTextarea">Pesan</label>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="g-recaptcha scale-down" data-sitekey="6Le1TackAAAAACyDZaXJ-yONpVpThpBi7lfKgySB"></div>
                                        <button type="submit" class="btn btn-primary px-5 py-2 d-block mx-auto mx-lg-0 fw-bold mt-3">Submit</button>
                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="my-5 my-lg-4">
                            <h2 class="mb-1">Unit Pengelola Sampah Terpadu</h2>
                            <h5 class="fw-semibold">Dinas Lingkungan Hidup Provinsi DKI Jakarta</h5>
                            <address class="mt-5">
                                <strong>Alamat:</strong><br>
                                Jl. Mandala V No.67, RT.1/RW.2, Cililitan, Kec. Kramat
                                jati, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta
                                13640
                            </address>
                            <abbr title="Phone Number"><strong>Phone:</strong></abbr>
                            <a href="tel:0218092744" class="text-decoration-none text-dark">(021) 8092744</a> <br />
                            <abbr title="Email Address"><strong>Email:</strong></abbr>
                            <a href="mailto:uptpst@jakarta.go.id" class="text-decoration-none text-dark">uptpst@jakarta.go.id</a>

                            <ul class="d-flex gap-3 list-unstyled mt-5">
                                <li>
                                    <a href="https://www.instagram.com/upst.dlh/" target="_blank">
                                        <img src="~/assets/img/social-medias/ig.png" width="42" />
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.facebook.com/UPSTDinasLH" target="_blank">
                                        <img src="~/assets/img/social-medias/fb.png" width="42" />
                                    </a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/UPST_DLH" target="_blank">
                                        <img src="~/assets/img/social-medias/tw.png" width="42" />
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.youtube.com/channel/UCJdhhKZejU6CnBa1l33DHpw" target="_blank">
                                        <img src="~/assets/img/social-medias/yt.png" width="42" />
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

@section headerScripts{
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
}

@section scripts{
    <script>
        // Navbar solid when scroll down
        document.querySelector("nav").classList.add("bg-white");
        document.querySelector("ul.navbar-nav").classList.remove("nav-text-white");

        // Navbar solid when scroll down
        window.addEventListener("scroll", () => {
            if (window.scrollY > 80) {
                document.querySelector("nav").classList.add("shadow");
            } else {
                document.querySelector("nav").classList.remove("shadow");
            }
        });


        // Form Validation
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (() => {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            const forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.from(forms).forEach(form => {
                form.addEventListener('submit', event => {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
        })()
    </script>
}

UPST/Views/PengelolaanSampah/ITF/Data.cshtml
@{
    ViewData["Title"] = "Data - ITF";
    ViewBag.Menu = "Pengelolaan Sampah";
    ViewBag.SubMenu = "ITF";
    ViewBag.SubMenuNd = "ITFData";
}

<main class="container w-blog pb-5" style="padding-top: 120px">
    <section>
        <h1 class="fw-bold text-center title-page">@ViewData["Title"]</h1>
    </section>
    <section class="content px-2 px-lg-3 py-5">
        <div class="row justify-content-center">
            <div class="col">
                <!-- Isi Content-->
                <p class="text-center">😔 Konten belum diperbarui...</p>
            </div>
        </div>
    </section>
</main>




@section scripts{
    <script>

        // Navbar solid when scroll down
        document.querySelector("nav").classList.add("bg-white");
        document.querySelector("ul.navbar-nav").classList.remove("nav-text-white");

        // Navbar solid when scroll down
        window.addEventListener("scroll", () => {
            if (window.scrollY > 80) {
                document.querySelector("nav").classList.add("shadow");
            } else {
                document.querySelector("nav").classList.remove("shadow");
            }
        });
    </script>
}

UPST/Views/PengelolaanSampah/ITF/FAQ.cshtml
@{
    ViewData["Title"] = "FAQ - ITF";
    ViewBag.Menu = "Pengelolaan Sampah";
    ViewBag.SubMenu = "ITF";
    ViewBag.SubMenuNd = "ITFFAQ";
}

<main class="container w-blog pb-5" style="padding-top: 120px">
    <section>
        <h1 class="fw-bold text-center title-page">@ViewData["Title"]</h1>
    </section>
    <section class="content px-2 px-lg-3 py-5">
        <div class="row justify-content-center">
            <div class="col">
                <!-- Isi Content-->
                <p class="text-center">😔 Konten belum diperbarui...</p>
            </div>
        </div>
    </section>
</main>




@section scripts{
    <script>

        // Navbar solid when scroll down
        document.querySelector("nav").classList.add("bg-white");
        document.querySelector("ul.navbar-nav").classList.remove("nav-text-white");

        // Navbar solid when scroll down
        window.addEventListener("scroll", () => {
            if (window.scrollY > 80) {
                document.querySelector("nav").classList.add("shadow");
            } else {
                document.querySelector("nav").classList.remove("shadow");
            }
        });
    </script>
}

UPST/Views/PengelolaanSampah/PKM/Data.cshtml
@{
    ViewData["Title"] = "Data - PKM";
    ViewBag.Menu = "Pengelolaan Sampah";
    ViewBag.SubMenu = "Pengelolaan Sampah Kawasan";
    ViewBag.SubMenuNd = "PKMData";
}

<main class="container w-blog pb-5" style="padding-top: 120px">
    <section>
        <h1 class="fw-bold text-center title-page">@ViewData["Title"]</h1>
    </section>
    <section class="content px-2 px-lg-3 py-5">
        <div class="row justify-content-center">
            <div class="col">
                <!-- Isi Content-->
                <p class="text-center">😔 Konten belum diperbarui...</p>
            </div>
        </div>
    </section>
</main>




@section scripts{
    <script>

        // Navbar solid when scroll down
        document.querySelector("nav").classList.add("bg-white");
        document.querySelector("ul.navbar-nav").classList.remove("nav-text-white");

        // Navbar solid when scroll down
        window.addEventListener("scroll", () => {
            if (window.scrollY > 80) {
                document.querySelector("nav").classList.add("shadow");
            } else {
                document.querySelector("nav").classList.remove("shadow");
            }
        });
    </script>
}

UPST/Views/Shared/_Footer.cshtml
<footer class="container-fluid border-2 border-top py-4 bg-white">
    <div class="container">
        <div class="row gap-4 gap-md-0 py-4">
            <div class="col-md-4">
                <div class="h-100 mb-5">
                    <img data-lazy="/assets/img/logo-upst.png"
                         class="lazy"
                         alt="Logo UPST"
                         width="125px"
                         height="auto" />
                    <h3 class="fs-6 mt-4">Unit Pengelola Sampah Terpadu</h3>
                    <h3 class="fs-6">Dinas Lingkungan Hidup Provinsi DKI Jakarta</h3>
                    <p class="mt-3">
                        Jl. Mandala V No.67, RT.1/RW.2, Cililitan, Kec. Kramat jati,
                        Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13640
                    </p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="row gap-4 gap-md-0">
                    <div class="col-md-3"></div>
                    <div class="col-md-3"></div>
                    <div class="col-md-3">
                        <ul class="d-flex flex-column gap-2 list-unstyled fw-medium">
                            <li class="fw-bold">TPST Bantargebang</li>
                            <li> <a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="TPSTRingkasan">Ringkasan</a></li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="TPSTData">Data</a></li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="TPSTFAQ">FAQ</a></li>
                        </ul>
                        <ul class="d-flex flex-column gap-2 list-unstyled fw-medium mt-4">
                            <li class="fw-bold">Pengelolaan Sampah</li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="PKMRingkasan">Ringkasan</a></li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="PKMData">Data</a></li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="PKMFAQ">FAQ</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <ul class="d-flex flex-column gap-2 list-unstyled fw-medium">
                            <li class="fw-bold">ITF</li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="ITFRingkasan">Ringkasan</a></li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="ITFData">Data</a></li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="ITFFAQ">FAQ</a></li>
                        </ul>
                        <ul class="d-flex flex-column gap-2 list-unstyled fw-medium mt-4">
                            <li class="fw-bold">JRC</li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="JRCRingkasan">Ringkasan</a></li>
                            <li><a class="text-decoration-none text-dark" asp-controller="PengelolaanSampah" asp-action="JRCMekanisme">Mekanisma</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-between align-items-center flex-column-reverse flex-md-row my-3">
            <div class="fw-semibold text-center">
                ©2023 Unit Pengelola Sampah Terpadu
            </div>
            <ul class="d-flex justify-content-center gap-4 list-unstyled">
                <li>
                    <a href="https://www.instagram.com/upst.dlh/" target="_blank">
                        <img data-lazy="/assets/img/social-medias/ig.png" class="lazy" width="32" />
                    </a>
                </li>
                <li>
                    <a href="https://www.facebook.com/UPSTDinasLH" target="_blank">
                        <img data-lazy="/assets/img/social-medias/fb.png" class="lazy" width="32" />
                    </a>
                </li>
                <li>
                    <a href="https://twitter.com/UPST_DLH" target="_blank">
                        <img data-lazy="/assets/img/social-medias/tw.png" class="lazy" width="32" />
                    </a>
                </li>
                <li>
                    <a href="https://www.youtube.com/channel/UCJdhhKZejU6CnBa1l33DHpw"
                       target="_blank">
                        <img data-lazy="/assets/img/social-medias/yt.png" class="lazy" width="32" />
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>

UPST/Views/Shared/_Navigation.cshtml
<nav class="navbar bg-white bg-opacity-75 backdrop-blur navbar-expand-lg position-fixed w-100 shadow-none border-bottom border-2 border-light-subtle">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <img src="~/assets/img/logo-upst.png"
                 alt="Logo UPST"
                 width="auto"
                 height="45" />
        </a>

        <button id="toggler-nav"
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <!-- <span class="navbar-toggler-icon"></span> -->
            <img src="~/assets/svg/list.svg" alt="Menu Toggler" />
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav gap-2 ms-auto mb-2 mb-lg-0 fw-semibold nav-text-white px-2 py-3 py-md-0">
                <li class='nav-item'>
                    <a class="nav-link @(ViewBag.Menu == "Beranda" ? "d-none" : "")" asp-controller="Home" asp-action="Index">Beranda</a>
                </li>
                <li class="nav-item dropdown">
                    <a class='nav-link dropdown-toggle @(ViewBag.Menu == "Profil" ? "active" : "")' href="#">
                        Profil
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="nav-link dropdown-item @(ViewBag.SubMenu == "Tentang Kami" ? "active" : "")" asp-controller="Profile" asp-action="Index">Tentang Kami</a>
                        </li>
                        <li>
                            <a class='nav-link dropdown-item @(ViewBag.SubMenu == "Struktur Organisasi UPST" ? "active" : "")' asp-controller="Profile" asp-action="StrukturOrganisasi">Struktur Organisasi</a>
                        </li>

                        <li>
                            <a class='nav-link dropdown-item @(ViewBag.SubMenu == "Galeri" ? "active" : "")' asp-controller="Profile" asp-action="Galeri">Galeri</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class='nav-link dropdown-toggle @(ViewBag.Menu == "Pengelolaan Sampah" ? "active" : "")' href="#">Pengelolaan Sampah</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class='nav-link dropdown-item dropdown-toggle @(ViewBag.SubMenu == "TPST Bantargebang" ? "active" : "")' href="#">TPST Bantargebang</a>
                            <ul class="dropdown-menu">
                                <li><a class='nav-link dropdown-item @(ViewBag.SubMenuNd == "TPSTRingkasan" ? "active" : "")' asp-controller="PengelolaanSampah" asp-action="TPSTRingkasan">Ringkasan</a></li>
                                <li><a class='nav-link dropdown-item @(ViewBag.SubMenuNd == "TPSTData" ? "active" : "")' asp-controller="PengelolaanSampah" asp-action="TPSTData">Data</a></li>
                                <li><a class='nav-link dropdown-item @(ViewBag.SubMenuNd == "TPSTLandfill" ? "active" : "")' asp-controller="PengelolaanSampah" asp-action="TPSTLandfill">Landfill</a></li>
                                <li><a class='nav-link dropdown-item @(ViewBag.SubMenuNd == "TPSTPLTSa" ? "active" : "")' asp-controller="PengelolaanSampah" asp-action="TPSTPLTSA">PLTSa</a></li>
                                <li><a class='nav-link dropdown-item @(ViewBag.SubMenuNd == "TPSTFAQ" ? "active" : "")' asp-controller="PengelolaanSampah" asp-action="TPSTFAQ">FAQ</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="nav-link dropdown-item dropdown-toggle @(ViewBag.SubMenu == "Pengelolaan Sampah Kawasan" ? "active" : "")" href="#">Pengelolaan Sampah Kawasan</a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link dropdown-item @(ViewBag.SubMenuNd == "PKMRingkasan" ? "active" : "")" asp-controller="PengelolaanSampah" asp-action="PKMRingkasan">Ringkasan</a></li>
                                <li><a class="nav-link dropdown-item @(ViewBag.SubMenuNd == "PKMData" ? "active" : "")" asp-controller="PengelolaanSampah" asp-action="PKMData">Data</a></li>
                                <li><a class="nav-link dropdown-item @(ViewBag.SubMenuNd == "PKMFAQ" ? "active" : "")" asp-controller="PengelolaanSampah" asp-action="PKMFAQ">FAQ</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="nav-link dropdown-item dropdown-toggle @(ViewBag.SubMenu == "ITF" ? "active" : "")" href="#">ITF</a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link dropdown-item @(ViewBag.SubMenuNd == "ITFRingkasan" ? "active" : "")" asp-controller="PengelolaanSampah" asp-action="ITFRingkasan">Ringkasan</a></li>
                                <li><a class="nav-link dropdown-item @(ViewBag.SubMenuNd == "ITFData" ? "active" : "")" asp-controller="PengelolaanSampah" asp-action="ITFData">Data</a></li>
                                <li><a class="nav-link dropdown-item @(ViewBag.SubMenuNd == "ITFFAQ" ? "active" : "")" asp-controller="PengelolaanSampah" asp-action="ITFFAQ">FAQ</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="nav-link dropdown-item dropdown-toggle @(ViewBag.SubMenu == "JRC" ? "active" : "")">JRC</a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link dropdown-item @(ViewBag.SubMenuNd == "JRCRingkasan" ? "active" : "")" asp-controller="PengelolaanSampah" asp-action="JRCRingkasan">Ringkasan</a></li>
                                <li><a class="nav-link dropdown-item @(ViewBag.SubMenuNd == "JRCMekanisme" ? "active" : "")" asp-controller="PengelolaanSampah" asp-action="JRCMekanisme">Mekanisme</a></li>
                            </ul>
                        </li>
                        <!--
                        <li>
                            <a class="nav-link dropdown-item dropdown-toggle" href="#">Lainnya</a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link dropdown-item" href="#">Ringkasan</a></li>
                                <li><a class="nav-link dropdown-item" href="#">Mekanisme</a></li>
                                <li><a class="nav-link dropdown-item" href="#">FAQ</a></li>
                                <li><a class="nav-link dropdown-item" href="#">Mekanisme</a></li>
                                <li>
                                    <a class="nav-link dropdown-item dropdown-toggle" href="#">Contoh Sub-Menu</a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="nav-link dropdown-item" href="#">Nested Sub Menu 1</a>
                                        </li>
                                        <li>
                                            <a class="nav-link dropdown-item" href="#">Nested Sub Menu 2</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        -->
                    </ul>
                </li>

                <li class="nav-item">
                    <a class="nav-link @(ViewBag.Menu == "Produk" ? "active" : "")" asp-controller="Produk" asp-action="Index">Produk</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link @(ViewBag.Menu == "Produk Hukum" ? "active" : "")" asp-controller="ProdukHukum" asp-action="Index">Produk Hukum</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(ViewBag.Menu == "Artikel" ? "active" : "")" asp-controller="Articles" asp-action="Index">Artikel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(ViewBag.Menu == "Kontak" ? "active" : "")" asp-controller="Kontak" asp-action="Index">Kontak</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-primary rounded-pill px-4 text-white"
                       href="https://pesapakawan.dinaslhdki.id/login">
                        Login
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<script>
    const dropdownToggle = document.querySelectorAll(".dropdown-toggle")
    dropdownToggle.forEach(dropdown => {
        dropdown.addEventListener('click', function () {
            this.nextElementSibling.classList.toggle("show")
        })
    })
</script>